// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qillftdqfztqfqlyjbkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbGxmdGRxZnp0cWZxbHlqYmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMDM5MzEsImV4cCI6MjA2MDc3OTkzMX0.lwQKyEpsfLbaVZkMAB79dEXFEXL_iIPN734Wt3oXbDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);